version: '3'
services:
  nginx:
    container_name: nginx
    image: 'nginx:stable'
    ports:
      - '80:80'
    links:
      - web
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
  web:
    container_name: poke
    build: ./web
    image: pokedex/app:${TAG}
    ports:
      - '3001:3001'
