apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-server
  labels:
    app: node
spec:
  selector:
    matchLabels:
      app: node
  replicas: 1
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-server
          image: moosequest/node-kubernetes:latest
          resources:
            requests:
              cpu: 100m
              memory: 100Mi
          ports:
          - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
  labels:
    app: node
spec:
  ports:
  - port: 3000
    targetPort: 3000
  selector:
    app: node
