apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokedex-app-deployment
  namespace: pokedex
spec:
  replicas: 2
  selector:
    matchLabels:
      app: pokedex-app
  template:
    metadata:
      labels:
        app: pokedex-app
    spec:
      containers:
        - name: pokedex-app-web
          image: pokedex-app-web:latest
          resources:
            requests:
              memory: '64Mi'
              cpu: '100m'
            limits:
              memory: '128Mi'
              cpu: '500m'
          ports:
          - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: pokedex-app-service
  namespace: pokedex
spec:
  ports:
  - port: 8081
    targetPort: 8081
    name: tcp
  selector:
    app: pokedex-app
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: pokedex-app-ingress
  namespace: pokedex
  annotations:
    kubernetes.io/ingress.class: 'traefik'
spec:
  rules:
  - host: 'www.192.168.0.31.sslip.io'
    http:
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: pokedex-app-service
              port:
                number: 8081
