global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
scrape_configs:
  - job_name:
    metrics_path: /metrics
    honor_labels: false
    honor_timestamps: true
    sample_limit: 0
